# Generated by Django 3.0.5 on 2020-04-30 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 30, 21, 16, 48, 475558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 4, 30, 21, 16, 48, 475558, tzinfo=utc)),
        ),
    ]
